### ISSUE TITLE
Open Source Code

### ISSUE THREAD

**Issue by ThePapaw** [MrKoyu/repo#1]
Now why would you do something like what you did? I don't know you, never tried to do anything to you. We should not try to fight among-st each other but help each other. Most all of the code that all the folks use today for all the modern add-ons was created by someone else and has been forked (copied) and modified and/or tweaked by the person working on it, to tailor it to their own needs or wishes.

What you did was kinda humorous actually, and sad as well, when I was first contacted by someone that was using both our add-ons, and they told me what happened, well I guess they deleted all your stuff. That is the sad part to me, they chose to not enjoy the great stuff you do because of your actions, and in THEIR words, _looked like you copy-n-pasted your photo onto the Fuzzy Britches logo_.  You may be forcing some of the great folks that enjoy your stuff to leave it. And to me, that is not good for the community. You are a major contributor, I am just a little peon doing this for my friends and family.

Ya know, I try to give credit to everyone in my files, including you. I do not try to steal, but take a fork of something or bits and pieces of it, as all of us have done, and modify it. I do it for personal use and friends. I do not seek glory from others, publish it to websites, youtube or anything. I even have it in my Readme's asking folks not post it on web sites or youtube without permission, **which no one ever has asked me permission for anything and have no clue who started posting it** .

Concerning the copy-n-paste, what do you think you started with? If you actually look into many of the files you have in your add-on, there is still references all the way back to and even before the original Exodus from your copy-n-pasting.

Open source is code that can be freely used, modified, improved, etc.. Fuzzy Britches is not a copy-n-paste of your Numbers add-on, but a combination of various pieces of code from many add-ons, including old non working stuff, as well as some of my own stuff. I have things in Fuzzy Britches that doesn't even work in Numbers, like library updates working with SMB shares, etc.. (**you are more than welcome to take some of my code and use it in Numbers if you wish, I would be glad to even offer you my help if needed**.)

See, I loved your thinking on how you implemented your artwork in your add-on and wanted to include that in Fuzzy Britches. I created my own from scratch, as I assume you did. I compliment you for it actually. It was a very cool idea. You should be proud of that. I love the artwork over the old plain text stuff.

I have great respect for all the folks that do this type of stuff, including you. Well I DID.

Ya know, there are enough forces out there that are trying to kill things like this, we should stand together and help each other and offer help to others that wish to come into it, ya know?

If I can help you in any way, let me know.

Keep up the great work you do, as will I  -The Papaw

**Comment by shellc0de27** [comment]
@ThePapaw why are you wasting your breath on this piece of crap copy n paster called numbers? That's what he does....steals everyone's work. Just like his pal eggman did. 
Anyways, after checking out ur addon.....looks like ur just as bad as numbers. I'm seeing scrapers that i have written and fixed. And yes i know what addon u took those from too. All with no credit pal. WHY?
And why lie in the addon news file? ie Scraper Work or Scrapers fixed. Truth is you haven't fixed any of them just like this numbers guy.
Also just a heads up you're DOUBLE SCRAPING which is a BIG NO NO!
Hope you clean up your addon, and give the right people credit before opening that mouth :)
